### ISSUE TITLE
experiments.py: error: argument --complex_state_dict_path: expected one argument

### ISSUE THREAD

**Issue by wj1108114106** [THU-KEG/MetaKGR#3]
when i run the commond "./experiment-rs.sh configs/fb15k-237-rs.sh --train 0 --few_shot", there exist a wrong: experiments.py: error: argument --complex_state_dict_path: expected one argument. i cannot understand it

**Comment by davidlvxin** [comment]
Sorry, it was my fault. This bug has been fixed in commits 7aad303.

**Comment by wj1108114106** [comment]
thank you for the prompt reply. Now it works.

**Comment by wj1108114106** [comment]
I also want to ask a simple question: how many GPUs have you used? because my machine owns only one GPU（1080ti），and i meet problem: out of memory. for this situation, can you give some suggestions? thanks.

**Comment by davidlvxin** [comment]
I only use one GPU (2080ti). You can reduce batch size to solve this problem (e.g., reduce `batch_size` and `train_batch_size` from 16 to 4 in [fb15k-237-rs.sh](https://github.com/THU-KEG/MetaKGR/blob/master/configs/fb15k-237-rs.sh)).

**Comment by wj1108114106** [comment]
thank you very much!
