### ISSUE TITLE
paraneters in experiment-emb.sh

### ISSUE THREAD

**Issue by wj1108114106** [THU-KEG/MetaKGR#5]
take "./experiment-emb.sh configs/FB15K-237-conve.sh --train 0" as example
source $1
exp=$2 
gpu=$3
ARGS=${@:4}

source means reload the environment variables.
gpu=$3     --gpu $gpu \  the parameter is 0(default)
but i cannot understand "exp=$2,  $exp \"
could you give me some suggestions, thanks

**Comment by davidlvxin** [comment]
$exp means that you choose training mode (--train) or test mode (--inference).
