### ISSUE TITLE
about the format of dataset

### ISSUE THREAD

**Issue by chrislouis0106** [THU-KEG/MetaKGR#7]
hi，
by reproducing the project of “Multihop with reward shaping”， I found that your datasets in MetaKGR are almost similar to Multihop-RS.  At the same time, in the Multihop-RS, the NELL-995 dataset is different from you's. Meanwhile, by the project "DeepPath", I saw the other NELL-995 dataset. So, I'm confused with the format of the dataset. And I tried to find the original dataset of NELL-995. But I failed. 
Another a small question, I don't sure that I think that "raw.kb = train.triple + dev.triple + test.triple” which is right or not. 
If you could help me, I will appreciate it. 
Best wishes

**Comment by davidlvxin** [comment]
The NELL dataset in our work is derived from [Multihop-RS](https://github.com/salesforce/MultiHopKG). I did some processing on NELL-995 (from Multihop-RS) because the test set of the original NELL-995 data set only contains a small number of relations. In our work, we treat NELL-995 from Multihop-RS as the original dataset of NELL-995.

For the second question, `raw.kb` is equal to `train.triple` in our work.

**Comment by chrislouis0106** [comment]
Thank you very much. 
the dataset in your project is easy to understand. But I don't sure how you get it by the NELL-995 in the Multihop-RS and could you explain it detailedly. 
![image](https://user-images.githubusercontent.com/31423097/90745720-e898f700-e302-11ea-85af-9b6004458cd8.png) 
![image](https://user-images.githubusercontent.com/31423097/90745875-f2225f00-e302-11ea-93b2-769ea2f8df5e.png)
another little problem, in my opinion, I feel that the raw is the original NELL-995 dataset. But I found that the size of raw.kb in the Multihop-RS is different from the size of raw.kb in MetakGR project. I don't know why and I don't found the original NELL-995 dataset.

**Comment by davidlvxin** [comment]
I randomly split the `raw.kb` in Multihop-RS and generate `train.triples`/`dev.triples`/`test.triples`. There is no problem with this processing, but there are some differences with the original NELL-995 in Multihop-RS. You can refer to README in [here](https://github.com/salesforce/MultiHopKG/blob/master/data-release.tgz) to understand the composition of the original NELL-995 in Multihop-RS.

**Comment by chrislouis0106** [comment]
Enn, I got it.  And I sum the length of files "train, dev, test" and found that the sum length is not equal to the length of raw.kb in the Multihop-RS. I don't know why. Haa.

**Comment by chrislouis0106** [comment]
en, if you continue the work, I would like to add your WeChat and discuss with you about your project and Multihop project.
Best wished!
