### ISSUE TITLE
help

### ISSUE THREAD

**Issue by PeifengRen** [THU-KEG/MetaKGR#8]
您好请问在增强学习过程中，策略网络中的θ参数是如何更新的，我在代码中没有找到，这个地方有点疑惑，谢谢~

**Comment by davidlvxin** [comment]
策略网络的参数更新在[这里](https://github.com/THU-KEG/MetaKGR/blob/7aad3038258adf65b3d4db34a9033785f0019aeb/src/rl/graph_search/pg.py#L60)，meta的参数更新在[这里](https://github.com/THU-KEG/MetaKGR/blob/7aad3038258adf65b3d4db34a9033785f0019aeb/src/rl/graph_search/pg.py#L47)。

**Comment by PeifengRen** [comment]
谢谢！
